app/authorization/routes.py
from flask import Blueprint, render_template, redirect, request, flash, url_for
from app.forms import signInForm, signUpForm, updateUser
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

from app.models import db, User

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form= signUpForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(form.username.data, form.email.data, form.password.data, form.first_name.data, form.last_name.data)

            try:
                db.session.add(new_user)
                db.session.commit()
            except:
                flash('Someone beat you to it. Username or email already exists, please try again.', category='alert-danger')
                return redirect(url_for('auth.signup'))

            flash(f'You have successfully signed up with the username {form.username.data}. You are now signed in.', category='alert-success')
            login_user(new_user)
            return redirect(url_for('home'))
        else:
            flash('Nop, invalid input, please try again.', category='alert-danger')
            return redirect(url_for('auth.signup'))
    return render_template('signup.html', form=form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    form = signInForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            usernamedata = form.username.data
            passworddata = form.password.data

            user = User.query.filter_by(username=usernamedata).first()
            if user is None or not check_password_hash(user.password, passworddata):
                flash('Incorrect username or password. Please try again.', category='alert-danger')
                return redirect(url_for('auth.signin'))

            login_user(user)
            flash(f'You are now logged in! Welcome { usernamedata}.', category='alert-success')
            return redirect(url_for('home'))
        else:
            flash('Incorrect username or password. Please try again.', category='alert-danger')
            return redirect(url_for('auth.signin'))
    return render_template('signin.html', form=form)

@auth.route('/signout')
def signout():
    logout_user()
    flash('You are now signed out.', category='alert-info')
    return redirect(url_for('auth.signin'))

@auth.route('/profile')
@login_required
def profile():
    context = current_user.to_dict()
    print(context)
    return render_template('profile.html', **context)
    
@auth.route('/updateuser', methods=['GET', 'POST'])
@login_required
def updateuser():
    form = updateUser
    if request.method == 'POST':
        if form.validate_on_submit() and check_password_hash(current_user.password, form.oldpassword.data):
            if form.newpassword.data and form.newusername.data:
                current_user.password = generate_password_hash(form.newpassword.data)
                current_user.username = form.newusername.data
                db.session.commit()

            elif form.newusername.data:
                current_user.username =  form.newusername.data
                db.session.commit()
            elif form.newpassword.data:
                current_user.password = generate_password_hash(form.newpassword.data)
                db.session.commit()
            flash('User information updated!', category='alert-info')
            return redirect(url_for('auth.profile' ))
        else:
            flash('Nop, invalid input. Please try again.', category='alert-danger')
            return redirect(url_for('auth.profile'))

    return render_template('updateuser.html', form=form)

app/templates/components/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title%} Marvel Or Die {% endblock title%}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/main.css">
</head>
  <body>
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="{{ url_for('home') }}">Marvel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('characters.addcharacter')}}">Add A Character</a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('auth.profile')}}">Profile</a> 
            <a class="nav-item nav-link" href="{{ url_for('auth.signout')}}">Sign Out</a>                       
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('auth.signin')}}">Sign In</a>
            <a class="nav-item nav-link" href="{{ url_for('auth.signup')}}">Register</a>
            {% endif %}
          </div>
        </div>
      </nav>
      <div class="row">
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert {{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}    
    </div>

      {% block content %}
      {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>